services:
  - type: web
    name: quizcomdash
    runtime: node
    buildCommand: cd .. && npm install && npm run build
    startCommand: cd .. && npm start
    envVars:
      - key: NODE_ENV
        value: production
